name: ecommernce
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1


environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
    #utility pakages
  flutter_native_splash: ^2.4.2
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.1.10
  iconsax: ^0.0.8
  carousel_slider: ^5.0.0
  get: ^4.6.5
  intl: ^0.17.0
   #device spec
  readmore: ^3.0.0

  #Icons
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logos/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/icons/categories/
    - assets/images/banners/
    - assets/images/products/
    - assets/icons/brands/
    - assets/images/content/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800